name: Build with .NET Core

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build Project
      run: dotnet build --no-restore --configuration Release
       
    - name: Execute unit tests
      run: dotnet test
